vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - svelte.svelte-vscode
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
ports:
  - name: SvelteKit dev server
    port: 5173
    visibility: public
tasks:
  - init: |

      # Ensure p33py can be imported
      gp env PYTHONPATH=$GITPOD_REPO_ROOT

      # Install dependencies
      pip3 install -r requirements.txt

      # Build scorecard and visualizations
      python3 build.py

      # Install web dependencies
      cd $GITPOD_REPO_ROOT/web
      npm install

      # Allow webserver to start
      gp sync-done installation

      # Enable git hooks
      git config core.hooksPath githooks/

  - command: |

      # Wait for installation to complete
      gp sync-await installation

      # Launch webserver
      cd $GITPOD_REPO_ROOT/web
      npm run dev

  - command: |

      # Open port, so we can preview
      gp ports await 5173

      # Open preview
      gp preview $(gp url 5173)
