vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - svelte.svelte-vscode
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
ports:
  - name: SvelteKit dev server
    port: 5173
    visibility: public
tasks:
  - name: Install Python dependencies
    init: pip3 install -r requirements.txt
  - name: Add project root to PYTHONPATH
    init: gp env PYTHONPATH=$GITPOD_REPO_ROOT
  - name: Enable git hooks
    init: git config core.hooksPath githooks/
  - name: Build scorecard and visualizations
    command: python3 build.py
  - name: start web dev server
    command: |
      cd $GITPOD_REPO_ROOT/web
      npm install
      npm run dev
  - name: open web server
    command: |
      gp ports await 5173
      gp preview $(gp url 5173)
