vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - svelte.svelte-vscode
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - bierner.markdown-mermaid
ports:
  - name: SvelteKit dev server
    port: 5173
    visibility: public
tasks:
  - init: |

      # Enable git hooks
      git config core.hooksPath githooks/

      # Ensure p33py can be imported
      gp env PYTHONPATH=$GITPOD_REPO_ROOT

      # Install dependencies
      PIP=pip3 ./scripts/install.sh

      # Allow webserver to start
      gp sync-done installation

      # Show readme
      code docs/gitpod.md

  - command: |

      # Wait for installation to complete
      gp sync-await installation

      # Launch webserver
      PYTHON=python3 WEB="$GITPOD_REPO_ROOT/web" ./scripts/start_dev.sh

  - command: |

      # Open port, so we can preview
      gp ports await 5173

      # Open preview
      gp preview $(gp url 5173)
