---
title: "DEI data cleannig"
author: "Mark"
date: '2022-07-26'
output: beamer_presentation
---

```{r readin, include=FALSE}
library("tidyverse")
library("dplyr")
library("tidyr")
library('ggfortify')
library('stargazer')
library('pscl')
```

#1 Read in datasets

```{r data, include=FALSE}
getwd()
setwd('E:/p33/P33-DEI-dashboard-project/DEI_CSV')

df_DEI_demo <- read.csv('df_demo.CSV')
df_DEI_parametric <- read.csv('df_parametrics.csv')

# lower cases in demo col
df_DEI_parametric_lower <- df_DEI_parametric %>%
  mutate(Demographic = tolower(Demographic))
```

#2 Clean Datas

## 2.1 df_DEI_parametric

```{r new variables}

# create cols of variables: var_x

df_DEI_parametric_mutated <- df_DEI_parametric_lower %>%
  
  ## create var_dim 
  mutate(var_dim = case_when(
    ### proficiency
    str_detect(Demographic,"proficient") ~ "proficiency",
    str_detect(Demographic,"persistent") ~ "proficiency",
    str_detect(Demographic,"conferral") ~ "proficiency",
    str_detect(Demographic,"benchmark") ~ "proficiency",
    str_detect(Demographic,"meets and exceeds") ~ "proficiency",
    str_detect(Demographic,"employee demographics") ~ "proficiency",
    ### access
    str_detect(Demographic,"enrollment") ~ "access",
    str_detect(Demographic,"enroll") ~ "access",
    ### excellence
    str_detect(Demographic,"advanced") ~ "excellence",
    str_detect(Demographic,"pass") ~ "excellence",
    str_detect(Demographic,"top three") ~ "excellence",
    str_detect(Demographic,"top") ~ "excellence", 
    str_detect(Demographic,"high") ~ "excellence",
    str_detect(Demographic,"exceeds") ~ "excellence",
    ### access
    str_detect(Demographic,"19-24") ~ "access",
    str_detect(Demographic,"19-24") ~ "access"
    )
  ) %>%
  mutate(var_dim = case_when(
    ## revision: three top school enrollment to excellence
    str_detect(Demographic,"mit") ~ "excellence",
    str_detect(Demographic,"stanford") ~ "excellence",
    str_detect(Demographic,"carnegie") ~ "excellence",
    TRUE ~ var_dim
    )
  ) %>%
  
  ## Create scope var.
  mutate(var_scope = case_when(
    str_detect(Demographic,"mit") | 
      str_detect(Demographic,"stanford") | 
        str_detect(Demographic,"carnegie") ~ "college",
    
    str_detect(Demographic,"msa") ~ "region_chi_msa",
    
    str_detect(Demographic,"cps") | 
      str_detect(Demographic,"in math") ~ "city_chi",
    
    str_detect(Demographic,"illinois") |
      str_detect(Demographic,"ibhe")~ "state_il",
    
    str_detect(Demographic,"usa") ~ "usa"
    )
  ) %>%
  
  ## create var_key.
  mutate(var_key = case_when(
    str_detect(Demographic,"math") ~ "math",
    
    str_detect(Demographic,"cs") ~ "cs",
    
    str_detect(Demographic,"stem") ~ "stem",
    
    str_detect(Demographic,"tech") |
      str_detect(Demographic,"jobs")~ "jobs",
    
    str_detect(Demographic,"sat") ~ "sat",
    
    str_detect(Demographic,"enrollment") | 
      str_detect(Demographic,"enroll") ~ "enrollment",
    
    str_detect(Demographic,"conferral") ~ "conferral"
    )
  ) %>%
    
  ## create var_key.
  mutate(var_stage = case_when(
    str_detect(Demographic,"4th") |
      str_detect(Demographic,"8th") |
        str_detect(Demographic,"k-8") ~ "k8",
    
    str_detect(Demographic,"sat") |
      str_detect(Demographic,"ap") |
        str_detect(Demographic,"hs") ~ "hs",
     
    str_detect(Demographic,"college") |
      str_detect(Demographic,"universities") |
        str_detect(Demographic,"degree") |
          str_detect(Demographic,"mit") | 
            str_detect(Demographic,"stanford") | 
              str_detect(Demographic,"computing") ~ "col",
    
    str_detect(Demographic,"employee") |
      str_detect(Demographic,"jobs") |
        str_detect(Demographic,"tech") ~ "emp")
  ) %>%
  
  ## create var_source
  mutate(var_source = str_extract(Demographic,"(?<=\\().+?(?=\\))")
          ) %>%
  
  ## create new var for ethnic groups (!!!!!!!!!!! minus others occured)
  mutate(Black_Hispanic = Black + Hispanic,
         White_Asian = White + Asian,
         others = All - Black - Hispanic - White - Asian) %>%
  
  select(All,Black_Hispanic,White_Asian,Black,Hispanic,White,Asian,others,everything())


colnames(df_DEI_parametric_mutated)


```


``` {r wide to long df}

df_DEI_parametric_mutated_long <- df_DEI_parametric_mutated %>%
  pivot_longer(1:8,names_to = "var_ethinc",values_to = "var_popul")



```
