---
title: "DEI data cleannig"
author: "Mark"
date: '2022-08-15'
output: beamer_presentation
---


```{r reading, include=FALSE}
library("tidyverse")
library("dplyr")
library("tidyr")
library('ggfortify')
library('stargazer')
library('pscl')
```

#1 Read in datasets

```{r data, include=FALSE}
getwd()
setwd('E:/p33/P33-DEI-dashboard-project/DEI_CSV_merged')

df_DEI_tidy <- read.csv('df_DEI_tidy.csv')
```

#2 Defining methodologies 

##2.1 Inequaty Index measurement of single metric by Pearcy and Keppel 2002 

```{r}

# two ethnic groups with geometric mean

func_II_DMPK_2_geo = function(n1,n2){
  p1 = n1
  n_avg = sqrt(n1*n2)
  inequality_index = (abs(n1 - n_avg) + abs(n2 - n_avg))/(2*n_avg)
  return(inequality_index)
}

# testing 
# ine_DMPK_2_geo(5,10)

# four ethnic groups with geometric mean
# DMPK_4_geo_scale

# two ethnic groups with arithmetic mean mean
# DMPK_2_ari_scale

# four ethnic groups with arithmetic mean mean
# DMPK_4_ari_scale

```

##2.2 extract values of metrics from dataset 

```{r}

func_II_DEI = function(df,metric1,metric2){
  df_metric1 = filter(df,
                metrics_new == metric1)
  value1 = df_metric1$population
  metric1 = df_metric1$metrics_new
  
  df_metric2 = filter(df,metrics_new == metric2)
  value2 = df_metric2$population
  metric2 = df_metric2$metrics_new
  
  ratio_onevstwo = value1/value2
  ratio_twovsone = value2/value1
  
  gap_twomione = value2-value1
  
  II = func_II_DMPK_2_geo(value1,value2)
  
  result = data.frame(metric_1 = value1,
                    metric_2 = value2,
                    ratio_1over2 = ratio_onevstwo,
                    ratio_2over1 = ratio_twovsone,
                    gap = gap_twomione,
                    Disparity_index = II
  )
  
  return(result)
  
}

# testing
unique(df_DEI_tidy$metrics_new)[1:3]
func_extract_DEI(df_DEI_tidy,"usa___2021___k8_4th___cs_classOffered___allSchools___all","usa___2021___k8_4th___cs_classOffered___allSchools___black_hispanic")

```



##2.3 Defining metrics

```{r}

# access : CPS K-8 STEM Magnet School Enrollment B/H vs CPS K-8 STEM magnet School W/A




```


##2.4 Scaling 

```{r}


func_scale_DEI = function(x1,w1,
                          x2,w2,
                          x3,w3,
                          x4,w4,
                          x5,w5,
                          x6,w6,
                          xmax,xmin){
  
}



```