---
title: "DEI data cleannig"
author: "Mark"
date: '2022-07-26'
output: beamer_presentation
---


```{r reading, include=FALSE}
library("tidyverse")
library("dplyr")
library("tidyr")
library('ggfortify')
library('stargazer')
library('pscl')
```

#1 Read in datasets

```{r data, include=FALSE}
getwd()
setwd('E:/p33/P33-DEI-dashboard-project/DEI_CSV')

df_DEI_demo <- read.csv('df_demo_08152022.csv')
df_DEI_parametric <- read.csv('df_parametrics_08152022.csv')

```

#2 Clean raw Dataset

## 2.1 df_DEI_parametric

```{r new variables}

# lower cases in demo col
df_DEI_parametric_lower <- df_DEI_parametric %>%
  mutate(Demographic = tolower(Demographic),
         var_est = tolower(var_est))

# label variables and education stage 
colnames(df_DEI_parametric_lower)

df_DEI_parametric_mutated <- df_DEI_parametric_lower %>%
  mutate(var_key = case_when(

    # uni and top uni   
     
    str_detect(Demographic,"mit enrollment") ~ "t3_mit_total_enrol",  
    str_detect(Demographic,"mit cs enrollment") ~ "t3_mit_cs_enrol",   
    str_detect(Demographic,"mellon enrollment") ~ "t3_mellon_total_enrol",  
    str_detect(Demographic,"carnegie mellon cs enrollment") ~ "t3_mellon_cs_enrol",
    str_detect(Demographic,"stanford enrollment") ~ "t3_stanford_total_enrol",
    str_detect(Demographic,"stanford cs enrollment") ~ "t3_stanford_cs_enrol",
    str_detect(Demographic,"top three illinois universities cs 2021 conferral") ~ "t3_cs_confer",
    str_detect(Demographic,"top three illinois universities cs 2022 conferral") ~ "t3_cs_confer",
    str_detect(Demographic,"top three usa universities cs conferral") ~ "t3_cs_confer",
    str_detect(Demographic,"top three usa universities cs enrollment") ~ "t3_cs_enrol", 
    str_detect(Demographic,"top three illinois universities cs 2021 enrollment") ~ "t3_cs_enrol", 
    str_detect(Demographic,"top three illinois universities cs 2022 enrollment") ~ "t3_cs_enrol", 
    str_detect(Demographic,"top three illinois universities 2021 conferral") ~ "t3_confer", 
    str_detect(Demographic,"top three illinois universities 2022 conferral") ~ "t3_confer", 
    str_detect(Demographic,"top three illinois universities 2021 enrollment") ~ "t3_enrol",  
    str_detect(Demographic,"top three illinois universities 2022 enrollment") ~ "t3_enrol", 
    str_detect(Demographic,"top three usa universities enrollment") ~ "t3_enrol",   
    str_detect(Demographic,"top three usa universities conferral") ~ "t3_confer", 
    
    str_detect(Demographic,"usa degree conferra") ~ "total_confer",
    str_detect(Demographic,"universities enrollment") ~ "total_enrol",
    str_detect(Demographic,"universities 2022 enrollment") ~ "total_enrol",
    str_detect(Demographic,"universities conferral") ~ "total_confer",
    
    # ap cs 
    str_detect(Demographic,"ap cs pass") ~ "apcs_pass",
    str_detect(Demographic,"ap cs enrollment") ~ "apcs_enrol",
    str_detect(Demographic,"ap cs enroll") ~ "apcs_enrol",
    str_detect(Demographic,"ap cs scored 3 or 4 ") ~ "apcs_score3/4",
    str_detect(Demographic,"ap cs scored 5") ~ "apcs_score5", 
    
    # cs  
    str_detect(Demographic,"offering cs") ~ "cs_classOffered",
    str_detect(Demographic,"interest in cs") ~ "cs_interested",
    str_detect(Demographic,"interested in computer science") ~ "cs_interested",
    str_detect(Demographic,"cs enrollment") ~ "cs_enrol",
    str_detect(Demographic,"cs/computing enrollment") ~ "cs_enrol",
    str_detect(Demographic,"cs 2022 enrollment") ~ "cs_enrol",
    str_detect(Demographic,"3 year cs degree conferral") ~ "cs3year_confer", 
    str_detect(Demographic,"3 year cs/computing conferral") ~ "cs3year_confer",
    str_detect(Demographic,"cs 2021 conferral") ~ "cs_confer",
    str_detect(Demographic,"cs degree conferral") ~ "cs_confer",
    str_detect(Demographic,"cs conferral") ~ "cs_confer",
    str_detect(Demographic,"computing conferral") ~ "cs_confer",
    
    # k-8
    str_detect(Demographic,"k-8 stem magnet school enrollment") ~ "mag_stem_enrol",
    
    # hs
    str_detect(Demographic,"magnet hs enrollment") ~ "mag_enrol", 
    str_detect(Demographic,"hs graduates") ~ "total_grad", 
    str_detect(Demographic,"dual credit") ~ "dualCredit", 
    
    # sat   
    str_detect(Demographic,"sat exceeds") ~ "sat_math_exceeds",
    str_detect(Demographic,"sat exceeds in math") ~ "sat_math_exceeds", 
    str_detect(Demographic,"sat benchmark") ~ "sat_bench", 
    str_detect(Demographic,"sat math bench mark ") ~ "sat_math_bench", 
    str_detect(Demographic,"sat meets and exceeds") ~ "sat_math_meet&exceeds", 
    
    # math   
    str_detect(Demographic,"failing algebra") ~ "math_algebra_fail",
    str_detect(Demographic,"enrolled in algebra") ~ "math_algebra_enrol",
    str_detect(Demographic,"advanced in math") ~ "math_advc",
    str_detect(Demographic,"advanced math") ~ "math_advc",
    str_detect(Demographic,"math advanced") ~ "math_advc",
    str_detect(Demographic,"proficient in math") ~ "math_prof",
    str_detect(Demographic,"math proficient and above") ~ "math_prof&abov",
    str_detect(Demographic,"below basic in math") ~ "math_belowBasic",
    str_detect(Demographic,"basic in math") ~ "math_basic",

    # employment
    str_detect(Demographic,"19-24 year olds in tech") ~ "csjob_t11_age19to24",
    str_detect(Demographic,"usa 19-24 employee") ~ "csjob_t11_age19to24",
    str_detect(Demographic,"top 3 highest paying cs jobs") ~ "csjob_t3",
    str_detect(Demographic,"employee demographics") ~ "csjob_t11",
    str_detect(Demographic,"11 top tech jobs") ~ "csjob_t11",
    
    # internet
    str_detect(Demographic,"aged 5-17 number of students without internet access") ~ "NOinternet_age5to17"
    )
  ) %>%
  
  # create educational stage
  mutate(var_grade = case_when(str_detect(Demographic,"4th") ~ "k8_4th",
                               str_detect(Demographic,"5th-8th") ~ "k8_5to8th",
                               str_detect(Demographic,"8th") ~ "k8_8th",
                               str_detect(Demographic,"k-8") |
                                 str_detect(Demographic,"5-17") ~ "k8_total",
     
    str_detect(Demographic,"college") |
      str_detect(Demographic,"universities") |
        str_detect(Demographic,"degree") |
          str_detect(Demographic,"carnegie mellon") |
            str_detect(Demographic,"mit") | 
              str_detect(Demographic,"stanford") | 
                str_detect(Demographic,"computing") ~ "col",
    
     str_detect(Demographic,"employment") |
       str_detect(Demographic,"employee") | 
         str_detect(Demographic,"jobs") |
           str_detect(Demographic,"tech") ~ "emp",  
    
    str_detect(Demographic,"sat") |
      str_detect(Demographic,"ap") |
        str_detect(Demographic,"9th-12th") |
          str_detect(Demographic,"hs") ~ "hs"
    )
  ) %>%
  
  ## Create scope var.
  mutate(var_scope = case_when(
    
    str_detect(Demographic,"usa") |
        str_detect(Demographic,"number of students") ~ "usa",    
    
    str_detect(Demographic,"mit") | 
      str_detect(Demographic,"stanford") | 
        str_detect(Demographic,"carnegie") ~ "college",
    
    str_detect(Demographic,"msa") |
        str_detect(Demographic,"19-24 year olds in tech workforce") ~ "region_chi_msa",
    
    str_detect(Demographic,"cps") | 
      str_detect(Demographic,"in math") ~ "city_chi",  	

    str_detect(Demographic,"illinois") |
        str_detect(Demographic,"ap cs") |
          str_detect(Demographic,"ibhe") |
          str_detect(Demographic,"3 year cs/computing") ~ "state_il"
    )
  ) %>%
  
  mutate(var_schoolType = case_when(
    str_detect(Demographic,"cps") |
      (str_detect(var_grade,"hs") & str_detect(var_scope,"city_chi")) |
      (str_detect(var_grade,"4th") & str_detect(var_scope,"city_chi"))|
      (str_detect(var_grade,"8th") & str_detect(var_scope,"city_chi"))|
      (str_detect(var_grade,"5th-8th") & str_detect(var_scope,"city_chi"))|
      (str_detect(var_grade,"k-8") & str_detect(var_scope,"city_chi"))|
      (str_detect(var_grade,"5-17") & str_detect(var_scope,"city_chi")) ~ "cps",
    TRUE ~ "allSchools"
    )
  )  %>%
  
  ## create var_dim 
  mutate(var_dim = case_when(
    
    ### excellence
    str_detect(Demographic,"scored 5") ~ "excellence",
    str_detect(Demographic,"advanced") ~ "excellence",
    str_detect(Demographic,"pass") ~ "excellence",
    str_detect(Demographic,"top three") ~ "excellence",
    str_detect(Demographic,"top") ~ "excellence", 
    str_detect(Demographic,"high") ~ "excellence",
    str_detect(Demographic,"exceeds") ~ "excellence",
    ### proficiency
    str_detect(Demographic,"scored 3") ~ "proficiency",
    str_detect(Demographic,"proficient") ~ "proficiency",
    str_detect(Demographic,"persistent") ~ "proficiency",
    str_detect(Demographic,"conferral") ~ "proficiency",
    str_detect(Demographic,"benchmark") ~ "proficiency",
    str_detect(Demographic,"meets and exceeds") ~ "proficiency",
    str_detect(Demographic,"employee demographics") ~ "proficiency",
    ### access
    str_detect(Demographic,"enrollment") ~ "access",
    str_detect(Demographic,"enroll") ~ "access",

    ### access
    str_detect(Demographic,"19-24") ~ "access",
    str_detect(Demographic,"amazon survey") ~ "access",
    str_detect(Demographic,"lack of internet access") ~ "access",
    str_detect(Demographic,"number of students") ~ "access",
    str_detect(Demographic,"amazon survey") ~ "access"
    )
  ) %>%
  
  mutate(var_dim = case_when(
    ## revision: three top school enrollment to excellence
    str_detect(Demographic,"mit") ~ "excellence",
    str_detect(Demographic,"stanford") ~ "excellence",
    str_detect(Demographic,"carnegie") ~ "excellence",
    TRUE ~ var_dim
    )
  ) %>%
  
  ## create var_source
  mutate(var_source = str_extract(Demographic,"(?<=\\().+?(?=\\))")
          ) %>%
  
  ## create new var for ethnic groups 
  mutate(Black_Hispanic = Black + Hispanic,
         White_Asian = White + Asian) %>%

  ## create var_type
  mutate(var_type = ifelse(All < 1,'prob','count')) %>%
  
  ## reorganize the order of cols for pivot_longer
  select(All,Black_Hispanic,White_Asian,Black,Hispanic,White,Asian,var_dim,everything())

colnames(df_DEI_parametric_mutated)

# check 
df_DEI_parametric_mutated %>%
  select(var_yr,Demographic,var_grade,var_key,var_scope,var_schoolType) %>%
  view()

```


```{r parametric df wide to long}

df_DEI_parametric_tidy <- df_DEI_parametric_mutated %>%
  pivot_longer(1:7,names_to = "var_ethnic",values_to = "population") %>%
  mutate(var_ethnic = tolower(var_ethnic)) %>%
  select(var_yr,var_scope,var_grade,var_key,var_ethnic,var_type,var_schoolType,population,everything())

colnames(df_DEI_parametric_tidy)

# write.csv(df_DEI_parametric_mutated_long,"E:/p33/P33-DEI-dashboard-project/df_DEI_parametric_tidy.csv", row.names = FALSE)

```

## 2.2 df_DEI_demo

```{R demographic df wide to long}

df_DEI_demo_long <- df_DEI_demo %>%
  mutate(Demographics = tolower(Demographics)) %>%
  select(-estimated) %>%
  pivot_longer(2:6,
               names_to = "var_ethnic",
               values_to = "population") %>%
  mutate(var_ethnic = tolower(var_ethnic)) 

```


```{r parametric df mutate}

# create cols of variables: var_x

df_DEI_demo_mutated_long <- df_DEI_demo_long %>%
  
  ## create var. of scope
  mutate(var_scope = case_when(
    str_detect(Demographics,"chicago msa") ~ "region_chi_msa", 
    
    str_detect(Demographics,"cps") |
      str_detect(Demographics,"chicago") |
        str_detect(Demographics,"all people in chicago") ~ "city_chi",
    
    str_detect(Demographics,"illinois") ~ "state_il",
    
    str_detect(Demographics,"us") |
      str_detect(Demographics,"usa") |
        str_detect(Demographics,"national") ~ "usa" )
    ) %>%
  
  ## educational stage
    mutate(var_stage = case_when(
      
    str_detect(Demographics,"4th") |
      str_detect(Demographics,"8th") |
        str_detect(Demographics,"k-8") ~ "k8",
    
    str_detect(Demographics,"9th") |
      str_detect(Demographics,"10th") |
        str_detect(Demographics,"11th") |
          str_detect(Demographics,"12th") |
            str_detect(Demographics,"sat") |
              str_detect(Demographics,"highschool") |
                str_detect(Demographics,"hs") ~ "hs",
     
    str_detect(Demographics,"college") |
      str_detect(Demographics,"degrees") |
        str_detect(Demographics,"18-24")  ~ "col",
    
    str_detect(Demographics,"employee") |
      str_detect(Demographics,"jobs") |
        str_detect(Demographics,"20-64") |
          str_detect(Demographics,"tech") |
            str_detect(Demographics,"us population") |
              str_detect(Demographics,"all people") ~ "emp")
    )%>%
  
  ## create var_source
  mutate(var_source = str_extract(Demographics,"(?<=\\().+?(?=\\))")
          ) %>%
  
  ## create variable of years
  mutate(var_yr = case_when(
    str_detect(Demographics,"2022") ~ 2022,
    str_detect(Demographics,"2021 - 2022") ~ 2021,
    str_detect(Demographics,"2020") ~ 2020,
    str_detect(Demographics,"2019") ~ 2019,
    str_detect(Demographics,"2017") ~ 2017,
    TRUE ~ 2021)) %>%
  
  ## create variable of school types
  mutate(var_schoolType = case_when(
    str_detect(Demographics,"cps") ~ "cps",
    str_detect(Demographics,"all") ~ 'allSchools',
    TRUE ~ 'allSchools')
    ) %>%
  
  ## create variable of grades
  mutate(x = case_when(
    str_detect(Demographics,"4th grade") ~ "k8_4th",
    str_detect(Demographics,"8th grade") ~ "k8_8th",
    str_detect(Demographics,"k-8") ~ "k8_total",
    
    str_detect(Demographics,"cps 9th grade") ~ "hs_9th",
    str_detect(Demographics,"cps 10th grade") ~ "hs_10th",
    str_detect(Demographics,"cps 11th grade") ~ "hs_11th",
   
    str_detect(Demographics,"cps 12th grade") |
      str_detect(Demographics,"hs seniors") ~ "hs_12th",
    
    str_detect(Demographics,"hs graduates") |
      str_detect(Demographics,"us highschool graduates") ~ "hs_grads",
    
    str_detect(Demographics,"cps hs") |
      str_detect(Demographics,"all highschool")|
        str_detect(Demographics,"highschool") |
            str_detect(Demographics,"us highschool population") ~ "hs_total",
    
    str_detect(Demographics,"sat takers") ~ "hs_SATtaker",
    str_detect(Demographics,"all college students") ~ "col_total",
    str_detect(Demographics,"all degrees conferred") ~ "col_conferred",
    
    str_detect(Demographics,"degree holders") ~ "degreeHolders_total",

    str_detect(Demographics,"us population") ~ "national_total",
    str_detect(Demographics,"all people in chicago ") ~ "city_total",
    str_detect(Demographics,"18-24") ~ "age_18to24",
    str_detect(Demographics,"20-64") ~ "age_20to64")
  )

colnames(df_DEI_demo_mutated_long)

```

```{r demo df tidy}

df_DEI_demo_tidy <- df_DEI_demo_mutated_long %>%
  rename(note = Demographics,
         var_grade = x) %>%
  mutate(population = format(population,scientific = FALSE)) %>%
  select(var_yr,var_scope,var_grade,var_schoolType,var_ethnic,population,note,var_sample,var_source)

# write.csv(df_DEI_demo_mutated_long,"E:/p33/P33-DEI-dashboard-project/df_DEI_demo_tidy_for_review 07281007.csv", row.names = FALSE)

```

# 3 Merge into one dataset (TBF)

## 3,1 rbind

```{r}

colnames(df_DEI_parametric_tidy)
colnames(df_DEI_demo_tidy)

# prepare parametric data for rbind

df_DEI_parametric_rbind <- df_DEI_parametric_tidy %>%
  select(1:8) %>%
   select(var_yr,var_scope,var_grade,var_key,var_schoolType,var_ethnic,population,var_type)

df_DEI_parametric_rbind$metrics_new <- paste(df_DEI_parametric_rbind$var_yr,
                                             df_DEI_parametric_rbind$var_scope,
                                             df_DEI_parametric_rbind$var_grade,
                                             df_DEI_parametric_rbind$var_key,
                                             df_DEI_parametric_rbind$var_schoolType,
                                             df_DEI_parametric_rbind$var_ethnic,
                                             sep = "___") 

# prepare demo data for rbind

df_DEI_demo_rbind <- df_DEI_demo_tidy %>%
  select(1:6) %>%
  mutate(var_key = "popul",
         var_type = "count") %>%
  select(var_yr,var_scope,var_grade,var_key,var_schoolType,var_ethnic,population,var_type)

df_DEI_demo_rbind$metrics_new <- paste(df_DEI_demo_rbind$var_yr,
                                       df_DEI_demo_rbind$var_scope,
                                       df_DEI_demo_rbind$var_grade,
                                       df_DEI_demo_rbind$var_key,
                                       df_DEI_demo_rbind$var_schoolType,
                                       df_DEI_demo_rbind$var_ethnic,
                                       sep = "___") 

colnames(df_DEI_parametric_rbind)
colnames(df_DEI_demo_rbind)

# rbind two datasets and create DEI tidy

df_DEI_tidy <- rbind(df_DEI_parametric_rbind,df_DEI_demo_rbind)

write.csv(df_DEI_tidy,"E:/p33/P33-DEI-dashboard-project/DEI_CSV_merged/df_DEI_tidy.csv", row.names = FALSE)


```
## 3,2 Merge into one dataset for plotting and caculating

```{r}

# preparing demo data for merging

df_DEI_tidy_formerge <- df_DEI_tidy %>%
  select(metrics_new,population) %>%
  pivot_wider(names_from = metrics_new,
              values_from = population) %>%
  mutate(rows = row_number())

df_DEI_tidy <- df_DEI_tidy %>%
  mutate(rows = row_number())

df_DEI_tidy_merged <- merge(df_DEI_tidy,df_DEI_tidy_formerge,by ="rows",all=TRUE) 

df_DEI_tidy_merged <- df_DEI_tidy_merged %>%
  fill(colnames(df_DEI_tidy_merged)[10:ncol(df_DEI_tidy_merged)]) %>%
  select(-rows) %>%
  select(metrics_new,everything())

write.csv(df_DEI_tidy_merged,"E:/p33/P33-DEI-dashboard-project/DEI_CSV_merged/df_DEI_tidy_merged.csv", row.names = FALSE)

```

