#!/usr/bin/env sh

# Installation: git config --set core.hooksPath ./githooks

# Run linting, testing, etc. scripts before committing

set -e

for script in ./scripts/pre-commit.*.sh; do
  eval "$script"
done
